[project]
dependencies = [
    "acp-sdk>=1.0.1",
    "ipykernel>=6.30.0",
    "jupyter>=1.1.1",
    "llama-index>=0.12.52",
]
description = "Add your description here"
name = "llama-index-packs-agent-context-protocol"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"
